// Builds dist/core.js (checker, runs in QJSEngine, no DOM) and dist/page.js + page.css (renderer, runs in WebEngine).
// dist/ is committed so building nebula needs no node; CI rebuilds it and fails when it is out of date.
import Ajv from 'ajv';
import standalone from 'ajv/dist/standalone/index.js';
import * as esbuild from 'esbuild';
import { copyFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { FRONT_MATTER } from './src/core/front.js';
import { components } from './src/components/index.js';

// Schemas are compiled to plain validation functions here, so the checker needs no runtime code generation
// (eval / new Function), which V4 handles incorrectly and which would be slower anyway.
const ajv = new Ajv({ allErrors: true, verbose: true, strict: true, allowUnionTypes: true, useDefaults: true, code: { source: true, esm: true } });
for (const c of components) ajv.addSchema(c.schema, c.name);
ajv.addSchema(FRONT_MATTER, 'frontMatter');
writeFileSync('src/core/validators.generated.js', '// generated by build.mjs from the component schemas; do not edit\n' + standalone(ajv));

mkdirSync('dist', { recursive: true });
const common = { bundle: true, minify: true, legalComments: 'none', logLevel: 'warning', charset: 'utf8' };
// QJSEngine (Qt's V4) implements ES2016 plus parts of later editions; lower everything newer.
// core stays unminified and ASCII-only: V4's parser rejects some raw non-ASCII string data, and readable stack traces help.
await esbuild.build({ ...common, minify: false, charset: 'ascii', entryPoints: ['src/core/index.js'], outfile: 'dist/core.js', format: 'iife', globalName: 'NebulaCore', target: 'es2016', platform: 'neutral', mainFields: ['module', 'main'] });
await esbuild.build({ ...common, entryPoints: ['src/page/index.js'], outfile: 'dist/page.js', format: 'iife', target: 'chrome108' });
await esbuild.build({ ...common, entryPoints: ['src/page/page.css'], outfile: 'dist/page.css', target: 'chrome108' });
copyFileSync('src/page/page.html', 'dist/page.html');
