// Builds dist/core.js (checker, runs in QJSEngine, no DOM) and dist/page.js + page.css (renderer, runs in WebEngine).
// dist/ is committed so building nebula needs no node; CI rebuilds it and fails when it is out of date.
import Ajv from 'ajv';
import standalone from 'ajv/dist/standalone/index.js';
import * as esbuild from 'esbuild';
import { copyFileSync, mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { readFile } from 'node:fs/promises';
import { dirname, relative, resolve } from 'node:path';
import { FRONT_MATTER } from './src/core/front.js';
import { components } from './src/components/index.js';

// Schemas are compiled to plain validation functions here, so the checker needs no runtime code generation
// (eval / new Function), which V4 handles incorrectly and which would be slower anyway.
const ajv = new Ajv({ allErrors: true, verbose: true, strict: true, allowUnionTypes: true, useDefaults: true, code: { source: true, esm: true } });
for (const c of components) ajv.addSchema(c.schema, c.name);
ajv.addSchema(FRONT_MATTER, 'frontMatter');
writeFileSync('src/core/validators.generated.js', '// generated by build.mjs from the component schemas; do not edit\n' + standalone(ajv));

mkdirSync('dist', { recursive: true });
const common = { bundle: true, minify: true, legalComments: 'none', logLevel: 'warning', charset: 'utf8' };
// QJSEngine (Qt's V4) implements ES2016 plus parts of later editions; lower everything newer.
// core stays unminified and ASCII-only: V4's parser rejects some raw non-ASCII string data, and readable stack traces help.
await esbuild.build({ ...common, minify: false, charset: 'ascii', entryPoints: ['src/core/index.js'], outfile: 'dist/core.js', format: 'iife', globalName: 'NebulaCore', target: 'es2016', platform: 'neutral', mainFields: ['module', 'main'] });
// echarts-gl imports echarts/zrender internals without extensions, which their package export maps do not allow
const deepImports = {
  name: 'echarts-deep-imports',
  setup(build) {
    build.onResolve({ filter: /^(echarts|zrender)\/lib\// }, (args) => ({ path: resolve('node_modules', `${args.path.replace(/\.js$/, '')}.js`) }));
  },
};
// claygl compiles size expressions with `new Function`; the page CSP has no 'unsafe-eval', so use an evaluator
const noEval = {
  name: 'claygl-no-eval',
  setup(build) {
    build.onLoad({ filter: /claygl[\\/]src[\\/]createCompositor\.js$/ }, async (args) => {
      const code = await readFile(args.path, 'utf8');
      const call = "new Function('width', 'height', 'dpr', 'return ' + exprRes[1])";
      if (!code.includes(call)) throw new Error('claygl changed: update the claygl-no-eval plugin in build.mjs');
      // a relative specifier: an absolute path would make the bundle depend on where the repository is checked out
      const helper = JSON.stringify(relative(dirname(args.path), resolve('src/page/sizeexpr.js')));
      return { contents: `import { compileSizeExpr } from ${helper};\n${code.replace(call, 'compileSizeExpr(exprRes[1])')}`, loader: 'js' };
    });
  },
};
// No identifier minification: with these plugins esbuild renames symbols differently from run to run, and CI
// checks that dist/ is reproducible. Syntax and whitespace minification are deterministic; the size cost is small
// for a bundle that is loaded from the binary, never over a network.
// An ES module with lazily loaded chunks (src/page/lazy/*): nebula serves every file under dist/ from the binary.
rmSync('dist/chunks', { recursive: true, force: true });
rmSync('dist/assets', { recursive: true, force: true });
await esbuild.build({ ...common, minify: false, minifySyntax: true, minifyWhitespace: true, entryPoints: { page: 'src/page/index.js' }, outdir: 'dist',
  format: 'esm', splitting: true, chunkNames: 'chunks/[name]-[hash]', assetNames: 'assets/[name]-[hash]', target: 'chrome108', plugins: [deepImports, noEval] });
for (const f of ['page.js', ...readdirSync('dist/chunks').map((c) => `chunks/${c}`)])
  if ((await readFile(`dist/${f}`, 'utf8')).match(/new Function\(|\beval\(/)) throw new Error(`dist/${f} contains eval / new Function, which the page CSP blocks`);
await esbuild.build({ ...common, entryPoints: ['src/page/page.css'], outfile: 'dist/page.css', target: 'chrome108' });
copyFileSync('src/page/page.html', 'dist/page.html');
